version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  web:
    build: .
    command: bash -c "python slack.py"
    volumes:
      - .:/app
    ports:
      - 8082:80
    env_file: .env
    depends_on:
      - redis
