version: '3'

services:
  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass wMD5rd2VgNa765Y7
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
  web:
    build: .
    command: bash -c "python slack.py"
    volumes:
      - .:/app
    ports:
      - 8082:80
    env_file: .env
    depends_on:
      - redis
